### ISSUE TITLE
API: Inverse Exp Messages Returned Incorrectly (global + bank)

### ISSUE THREAD

**Issue by Konnsalad** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#101]
**Device(please complete the following information):**
 - Device: Bridge6
 - Firmware version: v1.1.2
 - Hardware version: v1.0.1

**Describe the bug**
The device returns an incorrect sweep value for both bank and global exp messages set to any of the three inverse sweep types in subsequent API requests.
Unsure if it is either set incorrectly correctly on the device or just returned incorrectly (no screen).

**To Reproduce**
1. Send an API packet to the device that contains either bank or global exp messages with a sweep value set to one of:
    - invLinear
    - invLog
    - invReverseLog
3. Retrieve the settings via a DREQ command.
4. Note that the sweep types are returned incorrectly.

**Expected behavior**
The exp message sweep types should be returned correctly.

**Screenshots**
![ExpInvSweepTypes](https://user-images.githubusercontent.com/31266638/198923519-d1089e5e-4e13-4e8f-837d-29344607cd73.png)

**Additional context**
Config file with exp messages configured on bank 0.
[Bridge 6 _2022-10-31_14-03-53.txt](https://github.com/Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking/files/9897726/Bridge.6._2022-10-31_14-03-53.txt)

**Comment by samspencer5991** [comment]
fixed with v1.1.3
