### ISSUE TITLE
Smart message not saving in sequential switch

### ISSUE THREAD

**Issue by imranino** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#107]
**Device:**
 - Device: e.g. Bridge4
 - Firmware version: [e.g. v1.1.3]
 - Hardware version: e.g. v1.0

**Describe the bug**
using the web editor, I add a smart message as a sequential step, and it won't save

**To Reproduce**
1. Config switch to sequential
2. Add sequential step
3. custom>smart message>Go To Exp step>1
4. Save
6. it's no longer there

**Expected behavior**
should save

**Comment by samspencer5991** [comment]
This is a duplicate issue @imranino, see #94.

**Comment by imranino** [comment]
aha! Thanks, sorry I didn't see it!
