### ISSUE TITLE
LED/SEQUENTIAL bug and improvements suggestions

### ISSUE THREAD

**Issue by crazy-baboon** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#109]
**Device(please complete the following information):**
 - Device: Bridge 4 and 6
 - Firmware version: [e.g. v1.1.3]
 - Hardware version: [e.g. v1.0]

**Describe the bug**
- LED colours choosen in the APP are not well transfered to the device and change.
- In sequential mode, the label name not well appear on the bridge screen, the order of the label name step is not respected

**APP improvement suggestion**
- template/copy/paste of complete BANK and SWITCH config in the APP
- Sequential mode: possibility to swapp order of the step instead of rewrite everything if we want to introduce a new step in the middle of the sequence.
- same as precedent for all message in general, click and drop possibility should be nice to organize order of messages

**Comment by samspencer5991** [comment]
Hey mate, we really do need a lot more information for bug reports. It should include all steps and details required for someone to exactly replicate your experience. Can you please clarify?

**Comment by crazy-baboon** [comment]
Hi Sam,

I ll try to give more details.

SEQUENTIAL BUG :

I’m using Bridge 4 to control Bridge 6
Bridge 6 on channel midi 6

With Web editor I m trying to configure a setlist on the bridge 4



This is the configuration of the switch :



And this is the sequential messages :



Target is to change the bank of bridge 6 in the define order above. You could see that each label have the name of the track

Then I send to the devive Bridge 4 this configuration from the web editor.

On bridge 6 side, everything is ok for the sequential order and the bank switch in right order control change loading is correct), but of the bridge4, the label displayed are wrong…



Now, If i import the Bridge 4 configuration in the webeditor, you could see that some label have changed and that the colour also :



It seems it is a issue during the transfer from the WEBeditor to the device which change some label data
It is also a current bug for the choice of LED colour whatever the switch configuration.

I hope it is more clear now…

Do not hesitate for any further question

TRETON Fabien

De : Sam Spencer
Envoyé le :mercredi 23 novembre 2022 20:35
À : Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking
Cc : crazy-baboon; Author
Objet :Re: [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking] LED/SEQUENTIALbug and improvements suggestions (Issue #109)

Hey mate, we really do need a lot more information for bug reports. It should include all steps and details required for someone to exactly replicate your experience. Can you please clarify?

**Comment by samspencer5991** [comment]
Not sure if there is meant to be some images here to show the configuration, but they aren't visible for me?

**Comment by crazy-baboon** [comment]
Arf... i ll put that in a Word file...Thanks for the comment on my video (crazybaboon)Obtenir Outlook pour AndroidDe : Sam Spencer ***@***.***>Envoyé : mercredi 23 novembre 2022, 20:35À : Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking ***@***.***>Cc : crazy-baboon ***@***.***>; Author ***@***.***>Objet : Re: [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking] LED/SEQUENTIAL bug and improvements suggestions (Issue #109)
Hey mate, we really do need a lot more information for bug reports. It should include all steps and details required for someone to exactly replicate your experience. Can you please clarify?

**Comment by crazy-baboon** [comment]
With the word file

Fabien


De : Sam Spencer
Envoyé le :vendredi 25 novembre 2022 00:29
À : Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking
Cc : crazy-baboon; Author
Objet :Re: [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking] LED/SEQUENTIALbug and improvements suggestions (Issue #109)

Not sure if there is meant to be some images here to show the configuration, but they aren't visible for me?
