### ISSUE TITLE
Device locks up when trying to configure MIDI Thru

### ISSUE THREAD

**Issue by ChuckBarnard** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#12]
---

**Device(please complete the following information):**
 - Device: Bridge6
 - Firmware version: v1.0.1 both Beta 1 and Beta 2
 - Hardware version: [e.g. v1.0]

**Describe the bug**
When trying to access the MIDI thru settings the device locks up with all on the LEDs on red.  It changes the MIDI channel back to Omni.  This seems to have happened after changing the MIDI channel to something other then OMNI.  Even if I change it back to OMNI the issue still persists.

**To Reproduce**
1. Go to Menu - Global - MIDI - Thru Routing - TRS In or USB In

**Expected behavior**
Ideally it would be nice to be able to change the thru routing

**Screenshots**

**Additional context**

**Comment by samspencer5991** [comment]
Cannot replicate

**Comment by codemonk84** [comment]
@ChuckBarnard Would it be possible to grab a video to show your experience from start to end?

**Comment by ChuckBarnard** [comment]
Unfortunately I don't have a lot of process to show as I can't make it work.  It fails every time.  It doesn't look like I have the means to make a video small enough to attach.

**Comment by ChuckBarnard** [comment]
It looks like the device not retaining it's MIDI channel may be a separate bug.  I just power cycle and it is back to Omni.

**Comment by ChuckBarnard** [comment]
This appears to be working with Beta3
