### ISSUE TITLE
Bank names are not saving

### ISSUE THREAD

**Issue by ChuckBarnard** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#13]
**Device(please complete the following information):**
 - Device: Bridge6
 - Firmware version: v1.0.1 Beta2
 - Hardware version: [e.g. v1.0]

**Describe the bug**
Bank names are not saving

**To Reproduce**
Edit and save the bank name but when returning to the bank the name reverts back to what it was before. 

**Expected behavior**
Edits to the bank name should be retained.

**Comment by ChuckBarnard** [comment]
Bank names are still not saving with Beta 3

**Comment by samspencer5991** [comment]
Fixed with latest release
