### ISSUE TITLE
UI: Jack icon not having tip/ring animation for Flexiport configured as Switch Out

### ISSUE THREAD

**Issue by runeflobakk** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#15]
**Device:**
 - Device: Bridge4
 - Firmware version: v1.1.0.1_beta2
 - Hardware version: v1.0.1

**Describe the bug**
In the previous 1.0.x stable version, if you had a Flexiport configured as switch out, there was an icon continuously showing the state of the tip and ring. This does not seem to work anymore, as the icon is not updated when I trigger a switch output (the Flexiport output itself works as expected, just not the UI showing the tip/ring state). It also seem to be a bit random what the icon shows, as sometimes when I change to a bank, it can show either or both the tip and/or ring as active, though still not updating. Changing to another bank and back, or e.g. entering setup and exit will “reset” the icon to showing none as active.

**To Reproduce**
1. Set UI Mode to Extended UI
2. Set Flexiport 1 Mode to Switch Out
3. Configure a switch as Momentary
4. Setup a message when pressing the switch:
   Type: Smart message
   Function: TRS Switch
   Flexiport: Flexi1
   TRS: Tip
5. Setup a message when releasing the switch:
   Type: Smart message
   Function: TRS Switch
   Flexiport: Flexi1
   TRS: Open
6. Exit to main screen to see a jack plug icon displayed for Flexiport 1
7. Press and releasing the programmed switch does not affect the icon

**Expected behavior**
If setup correctly, the screen will have an icon for Flexiport 1 showing a jack plug. When pressing the programmed switch, the tip area of the jack icon should be filled, and similarly cleared when releasing the switch. The same is experienced for the ring of the jack.

The functionality of the Flexiport itself is however working as expected. This is only a UI bug, it seems.

**Screenshots**
![switch_config](https://user-images.githubusercontent.com/174823/168695826-ce787328-0611-4dc0-9f56-110c64d7d565.JPG)
![switch_message](https://user-images.githubusercontent.com/174823/168695834-1f9770c6-ef41-43c0-abb2-a287ff3b86cb.JPG)

https://user-images.githubusercontent.com/174823/168695911-a0597704-adb4-4e65-844f-896bff6bf671.mp4

**Comment by fourth44** [comment]
It's slightly more subtle:
When my Bridge4 boots, the icon is blank (as expected).
On Bank 0, I have a Bank message to activate tip+ring immediately. Going into Bank 0 the icon does correctly update to an activated tip+ring.
Within Bank 0, a footswitch will send out just Tip (essentially 'de-activating' Ring, it's for a Normally Closed Boss pedal) when pressed, returning to Tip+Ring when released. Here the icon does not change indeed.
It seems the icon does react to bank messages but not to footswitch messages.
