### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by HjorturLamhauge** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#17]
**Device(please complete the following information):**
 - Device: BRIDGE6
 - Firmware version: 1.1.0.1_beta2
 - Hardware version: v1.0.1

**Describe the bug**
Every time I boot the BRIDGE6 up, the original issue where the device freezes and LEDs go red when entering Thru Routing > USB In - returns. 
Factory resetting the device temporarily fixes the problem, which returns after the device has been power cycled.

**To Reproduce**
1. Go to 'Global > MIDI > Thru Routing > USB In' 
2. See error
3. Power cycle device
4. Go to 'System > Reset > Factory'
5. Confirm 
6. Go to 'Global > MIDI > Thru Routing > USB In 
7. See the lack of error
8. Power cycle
9. Go to 'Global > MIDI > Thru Routing > USB In' 
10. See error

**Expected behavior**
I expected the 1.1.0.1_beta2 to permanently fix the issue where BRIDGE6 freezes when entering: 'Global > MIDI > Thru Routing > USB In' 

**Screenshots**
![Screenshot 2022-05-16 at 12 42 26](https://user-images.githubusercontent.com/105918434/169509233-4273ff1d-50b4-446e-818b-9e6ca05c8fd6.jpg)

**Additional context**
Signal chain: Macbook Pro > (USB) > BRIDGE6 > (DIN5) > Disaster Area MIDI box 4 > Pedals

**Comment by samspencer5991** [comment]
Duplicate bug report
