### ISSUE TITLE
Hold Messages are not triggering

### ISSUE THREAD

**Issue by ChuckBarnard** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#20]
**Device(please complete the following information):**
 - Device: Bridge6
 - Firmware version:v1.0.1 Beta3
 - Hardware version: [e.g. v1.0]

**Describe the bug**

Either previously saved or newly created hold messages do  not fire. This is not working for either MIDI messages or smart messages

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by samspencer5991** [comment]
This is closed as hold functionality is now configured using the secondary footswitch actions.
