### ISSUE TITLE
P in switch name on lower switches not shown correctly

### ISSUE THREAD

**Issue by reneknuvers** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#22]
I named switch 3 'Damper', but the lower end of the lower cast p loses it's stick and thus it says DamDer where the second D is a SMALL CAPS D (or looks like it).

This is a cosmetic issue. Found this on the latest 1.1.0 beta 4, Bridge 6, HW rev 1.1

**Comment by samspencer5991** [comment]
This is not so much a bug as an unfortunate artifact of the layout of the live screen. The best option is to avoid lower case letters with stems.
