### ISSUE TITLE
Banking PC Outputs/USB=OFF transmits PC messages over USB midi (4 times)

### ISSUE THREAD

**Issue by fourth44** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#30]
Device: Bridge 4
Firmware: 1.1.0 beta 6
Hardwareversion: 1.0.1

**Describe the bug**
With Global/MIDI/Banking PC Outputs/USB set to off, when issuing a CTRL + goToBank command on the Device API, PC messages are transmitted from the bridge over USB MIDI.

**To Reproduce**
1. (Factory reset)
2. Disable Global/MIDI/Banking PC Outputs/USB
3. start a midi monitor on USB
4. send `0,CTRL~1,goToBank,3~` over the device API
5. observe 4 consecutive midi commands `b0 03 00`

**Expected behavior**
No PC messages over USB when PC Banking Outputs over USB are OFF, and especially not 4 times repeated.

**Additional context**
Otherwise all behaviour is normal.
There are no bank messages configured.
These midi commands are not send when manually changing banks on the Bridge.
Possibly related to #28: there issues are observed when USB=ON and turning USB to OFF stops these issues.

**Comment by samspencer5991** [comment]
@fourth44 I can't replicate this at all, following your steps exactly. I believe that I've fixed #28 but I'll let you verify that on the next beta build.
