### ISSUE TITLE
Freezing after Serial communication

### ISSUE THREAD

**Issue by GriffinSauce** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#36]
Sorry Sam, with Beta 7 this seems to be back for me.

**Device(please complete the following information):**
 - Device: Bridge6
 - Firmware version: 1.1.0-Beta7
 - Hardware version: 1.0.1

**Describe the bug**

After serial communication the device freezes, I've observed two behaviours:

**Issue 1: bank up/down, serial API freeze**
1. Factory reset
2. Send `0,CHCK~`
3. Device responds with device info
4. Bank down or up by pressing the relevant footswitches
5. Device response with `E,bankUp,7~`
6. Serial API stops responding until restart 

**Issue 2: footswitch, full freeze**
1. Factory reset
2. Send `0,CHCK~`
3. Device responds with device info
5. Press a single footswitch
6. Device responds with event
7. Footswitch lights up (sometimes) but the whole device stops responding until restart (no response from Serial API, footswitches, 1+4 long press or bank up/down switch combo's)

**Expected behavior**

For the device and API to stay responsive :D

**Screenshots**

**Additional context**

Serial terminal:
- I've encountered this with the JavaScript library but also confirmed the issue with the Arduino serial monitor and other serial terminals. The sending method does not matter.

Hardware:
- Macbook Air M1
- Macbook Pro intel
- Tried multiple cables, always directly connected

Data:
- I've done multiple factory resets, global settings resets, it doesn't matter what bank I am on.
- I _have_ in the past done restores of older `globalSettings` objects and banks, from backups across firmwares, so perhaps this has caused a corruption.

**Comment by GriffinSauce** [comment]
Update, some findings with previous beta's:
-  Beta 6:  same issues
- Beta 5:  worked initially but stopped after some testing and started behaving the same way. Reflashing firmware or factory reset did not fix it.

**Comment by fourth44** [comment]
What I found on linux + JVM: if I use MidiSystem.getMidiDeviceInfo + MidiSystem.getMidiDevice and open an receiver and transmitter (i.e. 'connect to the midi device'), serial communication won't hang. If I leave the midi connection out, serial communication will definitely hang, especially after CTRL.

**Comment by simonaglover95** [comment]
Is this still live, or needs closing?

**Comment by GriffinSauce** [comment]
I'll check this again with the latest firmware tonight/tomorrrow.

**Comment by GriffinSauce** [comment]
Yep, fixed in the latest beta! Thanks guys! 🙌
