### ISSUE TITLE
Change the word "Step" to "Value" for Smart Messages in "scrolling" category

### ISSUE THREAD

**Issue by simonaglover95** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#38]
Seeing as sequential mode uses "steps", and scrolling mode increments, decrements, or queues a "value", making the distinction in the naming of the smart messages may avoid confusion between the switch modes and their associated smart messages.

**Comment by samspencer5991** [comment]
fixed with v1.1.2
