### ISSUE TITLE
EXP sends message when no exp pedal plugged in

### ISSUE THREAD

**Issue by imranino** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#44]
Issue:
When I don’t have an expression pedal plugged into my Bridge 4, the advanced UI shows the pedal at ~85%. And this message (the assigned CC with a value somewhere around 110) gets sent at regular intervals. 

 This happens whenever I don’t have an expression pedal plugged in. This is revolved by always having an expression pedals plugged in, but sometimes I don’t want to bring one with me. 
 
Thanks! 

Running Bridge 4 on Firmware 1.1.0 Beta 6

**Comment by simonaglover95** [comment]
Hey Imran,

Way to avoid this is to change the Flexiport mode (it's a global setting so it only takes a second) when the exp isn't plugged in :) MIDI out will do the trick. 

Then change it back when you have an expression pedal plugged in
