### ISSUE TITLE
No midi output on v1.1.0.1beta

### ISSUE THREAD

**Issue by GriffinSauce** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#7]
**Device:**
 - Device: Bridge6
 - Firmware version: v1.1.0.1beta
 - Hardware version: v1.0.1

**Describe the bug**

There is no midi output on any of the outputs except for midi clock.

Details:
- Tried both switch messages and bank messages
- Tried both PC and CC messages
- Did a factory reset after FW install, both via the menu and by holding FS1 on startup
- Checked with Pocket midi and [Midi monitor](https://www.midimonitor.com/). Both show messages from other midi controllers with the same cables (2 known-good cables tried) and show the midi clock.

**To Reproduce**

1. Install FW v1.1.0.1beta
2. Reset to factory defaults
3. Press a switch

**Expected behavior**

Messages get sent and show up on monitors

**Screenshots**
N/a

**Additional context**

A potentially interesting sidenote: I cannot select the Bridge6 midi input in Pocket Midi, I have to go through a cable and my audio interface.

![image](https://user-images.githubusercontent.com/5630996/168040257-8c4f1841-3b74-4b1a-903a-23bd0d1d35a3.png)
![image](https://user-images.githubusercontent.com/5630996/168040308-e78d2bfb-5bdc-493c-bd9c-68dcc509c6df.png)

**Comment by hugowesterdahl** [comment]
exacly the same in my sistem.using Mac.doesnt send midi via USB or DIN.

**Comment by samspencer5991** [comment]
Yep, I've replicated this, a fix is inbound
