### ISSUE TITLE
Tap tempo display not updating

### ISSUE THREAD

**Issue by simonaglover95** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#80]
**Device(please complete the following information):**
 - Device: Bridge6
 - Firmware version: V1.1.1.1-beta4
 - Hardware version: v1.1

**Describe the bug**
Tap Tempo scribble strip not updating with taps

**To Reproduce**
Factory reset
Change fs 1 to tap tempo
Exit menu and tap new tempo 
Led speed updates, but not the scribble strip. 

**Expected behavior**
When tapping the switch, the tempo should update live on the OLED screen.

**Comment by simonaglover95** [comment]
When changing banks, display doesn't update, but entering menu and exiting again makes the tempo display change.

**Comment by simonaglover95** [comment]
More details: readout doesn't update on Fs1. On Fs2, the tempo updates but seems to be about double the actual tapped tempo. Fs3, seems to be normal function.

**Comment by samspencer5991** [comment]
@simonaglover95 is this fixed?

**Comment by simonaglover95** [comment]
No, still there on FS1 after factory reset

**Comment by samspencer5991** [comment]
Fixed in v1.1.2
