### ISSUE TITLE
API: Switch group bugs with partial data

### ISSUE THREAD

**Issue by GriffinSauce** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#85]
**Device(please complete the following information):**
 - Device: Bridge6
 - Firmware version: v1.1.1.1-beta.4
 - Hardware version: v1.0.1

**Describe the bug**

The API expects 8 switch groups, when only one is sent (the content doesn't seem to matter) the last item in the switch group is ignored.

**To Reproduce**

Send with DTXR `bankSettings`:
```
{
   // .. otherwise complete bank settings
  "switchGroups": [
    [
      {
        "switch": 0,
        "isPrimary": true,
        "broadcastMode": "txRx",
        "respondTo": "on",
        "responseType": "off"
      },
      {
        "switch": 1,
        "isPrimary": true,
        "broadcastMode": "txRx",
        "respondTo": "on",
        "responseType": "off"
      },
      {
        "switch": 2,
        "isPrimary": true,
        "broadcastMode": "txRx",
        "respondTo": "on",
        "responseType": "off"
      },
      {
        "switch": 3,
        "isPrimary": true,
        "broadcastMode": "txRx",
        "respondTo": "on",
        "responseType": "off"
      },
      {
        "switch": 5,
        "isPrimary": true,
        "broadcastMode": "txRx",
        "respondTo": "on",
        "responseType": "off"
      }
    ]
  ]
}
```

The last item is ignored. When an empty object `{}` is added to the end (or all switch groups are populated as empty arrays) it does get set correctly.

**Expected behavior**
When partial switch groups are sent either:
- OR the `switchGroups` are overwritten with the partial data + default empty data
- OR the partial data overwrites only those indexes
- OR an error that partial data is not allowed

But either way, no data from the switch group is lost of course. :)

**Comment by samspencer5991** [comment]
@GriffinSauce is this is happening with v1.1.1 public release?
