### ISSUE TITLE
LED is not properly set or cleared when switch (secondary) is set to Hold Momentary

### ISSUE THREAD

**Issue by frenno** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#90]
**Device:**
 - Device: Bridge6
 - Firmware version: 1.1.1
 - Hardware version: 1.0.1

**Describe the bug**
When a switch is set to "Hold Momentary" for it's secondary action, its LED isn't set to the correct state when entering that bank.

**To Reproduce**
1. In Bank 0, set switch 1 secondary config to "Hold Momentary", and set colour to green
2. Navigate to Bank 1, hold down Switch 1 so that the secondary aqua LED lights up
3. Navigate back to Bank 0
4. See error: the secondary LED of FS 1 is still lit up aqua.

**Expected behavior**
When a bank is entered, all LEDs should be set to their correct colour/state.

**Additional Info**
- If the secondary LED is set to "dim", it will be off if that LED was off in the previously accessed bank, or whatever colour that LED was if it was on.
- This occurs regardless if navigation between banks is using the FS1+FS2/FS2+FS3 footswitch combos, or if using "Go To Bank" Smart Messages are used

**Comment by samspencer5991** [comment]
Closed in v1.1.2
